Adding contact and about pages
devwilliamy/coverland pull request #248
Opened 2024-03-13 22:04 UTC by george-icarcover

2024-03-13 23:07 UTC, devwilliamy requested changes

2024-03-13 23:07 UTC, devwilliamy commented on src/app/(main)/about/page.tsx
> +});
Why do you need this here?

2024-03-13 23:07 UTC, devwilliamy commented on src/app/(main)/about/page.tsx
> +      </header>
You can just use my Header component from the policy pages, might have to spruce it up a bit but you should be able to reuse it

2024-03-15 17:54 UTC, george-icarcover commented on src/app/(main)/about/page.tsx
> +});
Its for the font family styling, I copied it from one of the other policy pages that somone made

2024-03-15 18:02 UTC, devwilliamy commented on src/app/(main)/contact/page.tsx
> +      console.log(value);
Get rid of console logs

2024-03-15 18:04 UTC, devwilliamy commented
15529 should not be on the same line

![image](https://github.com/devwilliamy/coverland/assets/156253900/744dd967-0ffb-49d7-8521-bac8ecfd208b)

Find out what these icons should do

![image](https://github.com/devwilliamy/coverland/assets/156253900/da5c6b0f-1246-439f-98f0-21832581bdc9)

I think the placeholder text should have a pl-1 so it's not right against the edge. Also find out how the email should work

![image](https://github.com/devwilliamy/coverland/assets/156253900/7bf3cfd6-7fbe-48d1-9b63-72ad524577c9)

2024-03-15 19:08 UTC, devwilliamy commented
This needs to be
Coverland
15529 Blackburn Ave
Norwalk, CA 90650

![image](https://github.com/devwilliamy/coverland/assets/156253900/0a25e8cf-c44d-4fac-90fb-d82dd817d718)

This should be 123-456-7890

![image](https://github.com/devwilliamy/coverland/assets/156253900/8431afd0-bd9a-4dba-91f9-e85dafa8d2cc)

This needs to be optional

![image](https://github.com/devwilliamy/coverland/assets/156253900/d1844ec8-71e1-420d-9aa9-1e1e539e2d72)

Can you also make sure it works on ur phone

2024-03-15 19:39 UTC, devwilliamy commented
Leaving this here but I'm not too worried about it

Bad phone number doesn't stop it

![image](https://github.com/devwilliamy/coverland/assets/156253900/68a64a22-f9d7-4e84-a695-0ade3a430f19)

Don't need the plus

![image](https://github.com/devwilliamy/coverland/assets/156253900/06867e59-3cf5-40a5-b3c3-1b1084927cdf)

Not a proper phone number

![image](https://github.com/devwilliamy/coverland/assets/156253900/c2febaaa-2399-4ab5-b96a-64f9d79a76e2)

2024-03-15 19:39 UTC, merged

2024-03-15 19:41 UTC, devwilliamy reviewed
LGTM