Added new My Orders page to User Profile (v1)
devwilliamy/coverland pull request #524
Opened 2024-06-13 16:44 UTC by coverlandjohnlee

-Version One
-Click Up : https://app.clickup.com/t/8688pw53e

-New page under /profile/orders
-My Orders returns 4 most recent user orders and displays a list of them with basic details

2024-06-14 01:15 UTC, devwilliamy requested changes
Overall pretty good, just want some clean up 👍 

Make sure to update the query to include COMPMLETED as well

2024-06-14 01:15 UTC, devwilliamy commented on src/lib/db/profile/ordersHistory.ts
> +};
TIL you can use `Pick`

```
export type TOrderItemProduct = Pick<TInitialOrdersDataDB, 'id' | 'name' | 'price'>;
```

Reasons to use `Pick`:
```
Type Safety: Ensures that properties exist in the original type.
Consistency: Automatically reflects changes in the original type. (this is cool)
Reduced Redundancy: Avoids duplicating property definitions.
Ease of Refactoring: Simplifies changes and updates.
Intellisense Support: Enhances developer experience with better code completion and documentation.
```

2024-06-14 01:15 UTC, devwilliamy commented on src/lib/db/profile/utils/money/index.ts
> +  }
Just like in the other PR, I suggest putting this in an example above the fnuction

2024-06-14 01:15 UTC, devwilliamy commented on src/lib/db/profile/utils/money/index.ts
> +    // Return the formatted value with a dollar sign
I have a feeling the comments are from ChatGPT so I get why they're here but if the line is pretty self explanatory, can clean it up

2024-06-14 01:15 UTC, devwilliamy commented on src/lib/db/profile/utils/date/index.ts
> +    const date = new Date(isoDateString);
If possible, include an example of what the isoDateString input should be as well

Also recommend putting this in the other date util file sinc ewe have them already

2024-06-14 01:15 UTC, devwilliamy commented on src/lib/db/profile/ordersHistory.ts
> +// fetchOrdersWithItemsAndProducts();
Clean this up

Don't forget to run Ctrl Shift F to make sure everything is formatted cleanly

2024-06-14 01:15 UTC, devwilliamy commented on src/lib/db/profile/ordersHistory.ts
> +    // })
Clean up

2024-06-14 01:15 UTC, devwilliamy commented on src/lib/db/profile/ordersHistory.ts
> +        .eq('status', 'COMPLETE')
This should look for COMPLETE or COMPLETED
Stripe; COMPLETE
Paypal: COMPLETED

2024-06-14 01:15 UTC, devwilliamy commented on src/app/(main)/profile/orders/page.tsx
> +  const orders: TInitialOrdersDataDB[] = await fetchUserRecentOrders(4);
Wrap in try catch

2024-06-14 16:26 UTC, devwilliamy requested changes
Added one more section for try catch

2024-06-14 16:26 UTC, devwilliamy commented on src/lib/db/profile/ordersHistory.ts
> +    const { data, error } = await supabase
I know some of our supabase calls aren't wrapped in a try catch but I think it would be good to have it for a db call.
Kinda surprised the other ones haven't really broken too much

Same for the other calls.

You would do something like 
```
 try {
    const { data, error } = await supabase
      .from<Order>(ADMIN_PANEL_ORDERS)
      .select('*'); // Adjust the query as needed

    if (error) {
      console.error('...")
      throw error; 
    }
```

2024-06-14 16:57 UTC, devwilliamy commented
I'm noticing some weird behavior and I'll probably record this in another click up for another time or task but if you're logged in and you're on another tab and come back into Coverland, it'll send you to the profile page for some reason

https://www.loom.com/share/0dc7dd450e9d47d28d92c15f0b3c5afa

2024-06-14 17:02 UTC, devwilliamy commented
Tested My Orders on desktop and mobile, looks good 👍

2024-06-14 19:07 UTC, merged

2024-06-14 19:38 UTC, devwilliamy commented
Was accidentally merged into preview

Reverted in #530
Re-applying in #531

2024-06-15 00:08 UTC, coverlandjohnlee commented on src/app/(main)/profile/orders/components/OrderItem.tsx
> +// import { TInitialOrderItemsDataDB } from '@/types';
[cda1dc2](https://github.com/devwilliamy/coverland/pull/531/commits/cda1dc2a76116847a237be281465c205247e5b19)
removed unused imports from OrderItem.tsx,  OrderItemCard.tsx, /profile/orders/page.tsx

2024-06-15 00:08 UTC, coverlandjohnlee commented on src/app/(main)/profile/orders/components/OrderItem.tsx
> +interface OrderItemProps {
[64f0221](https://github.com/devwilliamy/coverland/pull/531/commits/64f0221763ee6df9122ff3bfd24ff04f5947f498)

2024-06-15 00:09 UTC, coverlandjohnlee commented on src/app/(main)/profile/orders/components/OrderItem.tsx
> +        <div className="mt-4 mb-4 md:mt-2 md:mb-2 md:ml-5 md:w-3/5 pt-0 md:max-w-[325px]">
Didn't know they had margin by axes. Thanks
[e33316f](https://github.com/devwilliamy/coverland/pull/531/commits/e33316f56a8ed4220d341e90b76299e0e41c2476)

2024-06-15 00:09 UTC, coverlandjohnlee commented on src/app/(main)/profile/orders/components/OrderItem.tsx
> +          <div className="mb-1 text-base md:text-base text-[#707070]">
Ya I did end up refactoring common tailwind css properties to top-level div
[e33316f](https://github.com/devwilliamy/coverland/pull/531/commits/e33316f56a8ed4220d341e90b76299e0e41c2476)

2024-06-15 00:11 UTC, coverlandjohnlee commented on src/app/(main)/profile/orders/components/OrderList.tsx
> +      <Card className="m-3 p-2 md:m-0 md:m-1 md:mb-4">
[e33316f](https://github.com/devwilliamy/coverland/pull/531/commits/e33316f56a8ed4220d341e90b76299e0e41c2476)
Got rid of the m-0 and m-1

For the margin/padding one it's for this use-case:
![Screenshot 2024-06-14 162132](https://github.com/devwilliamy/coverland/assets/171850605/40156c11-d8d5-48dc-bf6d-61e9dc19ff4b)

Maybe there's a better way to do it but the "Card" is used both as a page/content wrapper here.

2024-06-15 00:12 UTC, coverlandjohnlee commented on src/app/(main)/profile/orders/components/OrderList.tsx
> +        <CardHeader className="p-2 pb-4 pt-4 text-xl font-bold md:p-4 md:text-xl">
[e33316f](https://github.com/devwilliamy/coverland/pull/531/commits/e33316f56a8ed4220d341e90b76299e0e41c2476)

I believe I caught redundant tailwind css

2024-06-15 00:15 UTC, coverlandjohnlee commented on src/app/(main)/profile/orders/page.tsx
> +  const orders: TInitialOrdersDataDB[] = await fetchUserRecentOrders(4);
[05ae438](https://github.com/devwilliamy/coverland/pull/531/commits/05ae4381163c40eb11f92780bdbd469ae9d108d8)
This one is a really good fix, thank you. Now if there is an issue with fetchUserRecentOrders, it defaults to an empty orders array:

![image](https://github.com/devwilliamy/coverland/assets/171850605/16f8f109-8040-4c0f-92cf-839bed97c599)

2024-06-15 00:16 UTC, coverlandjohnlee commented on src/app/(main)/profile/page.tsx
> +          </Link>
[9d2890c](https://github.com/devwilliamy/coverland/pull/531/commits/9d2890cfe7ef04bfe74970cb3569afdb34b313a4)
![Screenshot 2024-06-14 171605](https://github.com/devwilliamy/coverland/assets/171850605/1b537acf-5cea-4484-8a58-fdd7179311a0)

2024-06-15 00:17 UTC, coverlandjohnlee commented on src/components/profile/orders/OrderItemCard.tsx
> +    )
Oops
[704c222](https://github.com/devwilliamy/coverland/pull/531/commits/704c222d757d3b130ed7c7e5b348901c894553a7)
[b456988](https://github.com/devwilliamy/coverland/pull/531/commits/b45698852529f65cc27abf0e771e812569aa5d09)

2024-06-15 00:19 UTC, coverlandjohnlee commented on src/lib/db/profile/ordersHistory.ts
> +};
I love the idea of using Picks here thanks! I am actually using just the types imported from supabase <Table> for Orders, OrderItems, and Products so the ones I've created aren't being used currently (i.e. TOrderItemProduct). However, I plan to restructure these types and use them in v2, so I would like to keep them in this file for now.

2024-06-17 16:50 UTC, coverlandjohnlee commented on src/lib/db/profile/ordersHistory.ts
> +        .eq('status', 'COMPLETE')
[db9320e](https://github.com/devwilliamy/coverland/pull/531/commits/db9320e6f13aed367f2bb52cf03b402c6e8caeda)

2024-06-17 16:52 UTC, coverlandjohnlee commented on src/lib/db/profile/ordersHistory.ts
> +    // })
I'll keep my code clean as possible in subsequent PR. Lesson learned! Thanks for noticing my mess.
[3f19e43](https://github.com/devwilliamy/coverland/pull/531/commits/3f19e437e450328e5180d3491e426402c7679e49)

2024-06-17 16:54 UTC, coverlandjohnlee commented on src/lib/db/profile/utils/date/index.ts
> +    const date = new Date(isoDateString);
[628d3e1](https://github.com/devwilliamy/coverland/pull/531/commits/628d3e121122206bd17f90914e99f9e140f29586)
Good catch. I will check for existing util functions inside our /lib/utils and add my own util functions into here now.

2024-06-17 16:55 UTC, coverlandjohnlee commented on src/lib/db/profile/utils/date/index.ts
> +    const date = new Date(isoDateString);
Also added the comment with example above formatISODate

2024-06-17 16:55 UTC, coverlandjohnlee commented on src/lib/db/profile/utils/money/index.ts
> +    // Return the formatted value with a dollar sign
Yep! Caught me redhanded. Cleaned.
[db9b42d](https://github.com/devwilliamy/coverland/pull/531/commits/db9b42ddcfb30da3170977958305cc3ac59c8e67)

2024-06-17 16:59 UTC, coverlandjohnlee commented on src/lib/db/profile/utils/money/index.ts
> +  }
So I saw we had some util files already that have "money" related functions such as inside calculations.ts and stripe.ts. I added my own /utils/money.ts inside the email PR 526/529. Request to pull preview into this branch and move this formatMoney into there for better global access. If it's a git headache, I will do it in my john/preview-order-details-v2. That might be better: what do you think?

2024-06-17 17:04 UTC, coverlandjohnlee commented
> I'm noticing some weird behavior and I'll probably record this in another click up for another time or task but if you're logged in and you're on another tab and come back into Coverland, it'll send you to the profile page for some reason
> 
> https://www.loom.com/share/0dc7dd450e9d47d28d92c15f0b3c5afa

Oh yes I noticed this behavior too. It might be beneficial for us to design some global User context in our app eventually?

2024-06-17 17:07 UTC, coverlandjohnlee commented
@devwilliamy 

Thanks for such a thorough review on one of my first PR! I learned a lot.

2024-06-17 17:09 UTC, coverlandjohnlee commented
> > I'm noticing some weird behavior and I'll probably record this in another click up for another time or task but if you're logged in and you're on another tab and come back into Coverland, it'll send you to the profile page for some reason
> > https://www.loom.com/share/0dc7dd450e9d47d28d92c15f0b3c5afa
> 
> Oh yes I noticed this behavior too. It might be beneficial for us to design some global User context in our app eventually?

Clarification: I'm not sure what exactly is causing this behavior. Maybe there's a quick fix to it currently. I believe setting up a global User (signed in) context may resolve this specific issue. It would be useful to have for other User-related functionality down the road as well. I will put in a click up for now.

2024-06-17 17:14 UTC, coverlandjohnlee commented on src/lib/db/profile/ordersHistory.ts
> +    const { data, error } = await supabase
[3f19e43](https://github.com/devwilliamy/coverland/pull/531/commits/3f19e437e450328e5180d3491e426402c7679e49)
^ Added try catch for each supabase DB call
[7f48249](https://github.com/devwilliamy/coverland/pull/531/commits/7f4824952bc3a08ac511f5117b631ee5622680fe)
^ Ended up wrapping each step inside fetchUserRecentOrders as well

2024-06-17 18:06 UTC, devwilliamy commented on src/lib/db/profile/utils/money/index.ts
> +  }
General rule of thumb is yeah if there's a particular module that only uses it, I'll keep it there
But once other parts of the app use it then I'll move it out to something more generic 

Since this is formatMoney, doesn't really apply to calculations or stripe utils