Dynamic prices for low stock products
devwilliamy/coverland pull request #534
Opened 2024-06-17 20:44 UTC by george-icarcover

https://app.clickup.com/t/8688tztnr

2024-06-18 21:19 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    else if (quantityBetween4and10) {
I'm confused, am I supposed to trust the comment or the variable?

2024-06-18 21:19 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    else if (quantityBetween4and10) {
I'm confused, am I supposed to trust the comment or the variable?

2024-06-18 21:32 UTC, devwilliamy requested changes
It looks like car covers and seat covers have two different logics. 

Please also clean up unused code throughout your files changed.

2024-06-18 21:32 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +      console.log({ calcedPrice });
Please get into practice of going through your changes and cleaning up unneeded code

2024-06-18 21:32 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +  const [discountPercent, setDiscountPercent] = useState<string | null>('50%');
Why is this a string and not a number?

2024-06-18 21:32 UTC, devwilliamy commented on src/contexts/CarSelectionContext.tsx
>    }
What's happening here?

2024-06-18 21:32 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +  const [between4and10, setBetween4and10] = useState(false);
It's good practice that if something is a boolean, to prefix it with `is` 
eg. `isBetween1and3`

2024-06-18 21:32 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    if (between1and3 || between4and10) {
I don't think you need these variables, can just check if newMSRP is not 0

Unless you need these two for something else

2024-06-18 21:32 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +                ? newMSRP
Why are you checking newMSRP twice?

2024-06-18 21:32 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +              {discountPercent && <p>(-{discountPercent})</p>}
You don't need this `discountPercent` here because you are checking `discounPercent` at the top

2024-06-18 21:32 UTC, devwilliamy commented on src/app/(main)/seat-covers/components/SeatContent.tsx
> +  }, [selectedProduct]);
I'm confused why is this different?

2024-06-18 22:23 UTC, devwilliamy commented
In Add To Cart, the total price is going up. This was not something that was happening before

Production:
![image](https://github.com/devwilliamy/coverland/assets/156253900/18108eeb-24a9-4637-990d-4d79baa7a63a)


Your branch: 
![image](https://github.com/devwilliamy/coverland/assets/156253900/617c6b9c-d15d-4720-997e-afc6202f5520)

2024-06-18 22:35 UTC, devwilliamy commented
Installments is wrong
https://coverland-2-0-git-george-preview-low-e6619e-coverland-3615f02b.vercel.app/car-covers/premium-plus/audi/a6/1994-2011?submodel=avant
![image](https://github.com/devwilliamy/coverland/assets/156253900/2d7be9c5-5e30-46fe-94e8-d7197724d3b6)

https://coverland-2-0-git-george-preview-low-e6619e-coverland-3615f02b.vercel.app/car-covers/premium-plus/chevrolet/corvette/1997-2019
![image](https://github.com/devwilliamy/coverland/assets/156253900/d00b34d8-3642-4ed5-888f-b2e52793e67a)

2024-06-18 22:36 UTC, george-icarcover commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    else if (quantityBetween4and10) {
sorry, I forgot to update the comment, trust the code itself

Calvin let me know to change the values earlier today

2024-06-18 22:41 UTC, george-icarcover commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    else if (quantityBetween4and10) {
variable

2024-06-18 22:41 UTC, devwilliamy commented
The price being saved is also not right in order items table
Order ID : 2218

![image](https://github.com/devwilliamy/coverland/assets/156253900/4b3bbcba-7091-47a0-a167-56d64b85cf6f)

![image](https://github.com/devwilliamy/coverland/assets/156253900/1ae20dd0-a606-4eff-b362-7a7e8e1adbbe)

2024-06-18 22:45 UTC, devwilliamy commented
Seat covers:
https://coverland-2-0-git-george-preview-low-e6619e-coverland-3615f02b.vercel.app/seat-covers/leather/mercedes-benz/e-class/2017-2025?submodel=wagon

This should be quantity: 4, 25% but it's still at 50%
![image](https://github.com/devwilliamy/coverland/assets/156253900/5136f179-7491-433e-84b8-97bb8babff8c)

2024-06-18 22:46 UTC, devwilliamy commented
The styling here needs to be updated. This is for seat covers quantity : 0
https://coverland-2-0-git-george-preview-low-e6619e-coverland-3615f02b.vercel.app/seat-covers/leather/mercedes-benz/e-class/1996-2009?submodel=wagon
![image](https://github.com/devwilliamy/coverland/assets/156253900/f4c60437-bb39-408d-9cb0-2c67593dc1c6)

2024-06-18 22:50 UTC, george-icarcover commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +                ? newMSRP
Im checking if newMsrp is falsy value, so if it is just display the original msrp

2024-06-18 22:58 UTC, george-icarcover commented on src/app/(main)/seat-covers/components/SeatContent.tsx
> +  }, [selectedProduct]);
I forgot to change this one to 1-3 and 4-10

2024-06-18 23:01 UTC, george-icarcover commented on src/contexts/CarSelectionContext.tsx
>    }
Will remove, was just console logging the quantity

2024-06-19 00:15 UTC, george-icarcover commented
> Seat covers: https://coverland-2-0-git-george-preview-low-e6619e-coverland-3615f02b.vercel.app/seat-covers/leather/mercedes-benz/e-class/2017-2025?submodel=wagon
> 
> This should be quantity: 4, 25% but it's still at 50% ![image](https://private-user-images.githubusercontent.com/156253900/340859607-5136f179-7491-433e-84b8-97bb8babff8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NTU5OTcsIm5iZiI6MTcxODc1NTY5NywicGF0aCI6Ii8xNTYyNTM5MDAvMzQwODU5NjA3LTUxMzZmMTc5LTc0OTEtNDMzZS04NGI4LTk3YmI4YmFiZmY4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMDA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjY5YWM4ZGRmMzU1N2M3MjI2NTQyOWZkYmFmYTk3MDMyNjZjYjQwZmE5YmVmNzNkZWVjZGU5ZWY2N2M4NWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6otMHEHCtevXWdD3btRvg2QuU1LcNeXDWUFzmQjFVxQ)

select
  quantity,
  display_color,
  *
from
  "Products"
where
  CAST(quantity AS INTEGER) >= 0
  and year_generation = '2017-2020'
  and make_slug = 'mercedes-benz'
  and model_slug = 'e-class'
  and
type = 'Seat Covers'
limit
  300;

2024-06-19 16:19 UTC, george-icarcover commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +  const [discountPercent, setDiscountPercent] = useState<string | null>('50%');
c

2024-06-21 16:37 UTC, george-icarcover commented
> The price being saved is also not right in order items table Order ID : 2218
> 
> ![image](https://private-user-images.githubusercontent.com/156253900/340858928-4b3bbcba-7091-47a0-a167-56d64b85cf6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzA3MDQsIm5iZiI6MTcxODkzMDQwNCwicGF0aCI6Ii8xNTYyNTM5MDAvMzQwODU4OTI4LTRiM2JiY2JhLTcwOTEtNDdhMC1hMTY3LTU2ZDY0Yjg1Y2Y2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwMDQwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjgxNjI3NTdmOWYyNzZkMjE0MzBlOTdiOGFkNjBmNTcyYzMyNDFlMzIxYTE3MDBjZWMwMjk5Mzk1MDQxMWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7S9wIcZxE-31hCxtyo0kXsLytSyTsXo9pqnJX-9T-DI)
> 
> ![image](https://private-user-images.githubusercontent.com/156253900/340858951-1ae20dd0-a606-4eff-b362-7a7e8e1adbbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzA3MDQsIm5iZiI6MTcxODkzMDQwNCwicGF0aCI6Ii8xNTYyNTM5MDAvMzQwODU4OTUxLTFhZTIwZGQwLWE2MDYtNGVmZi1iMzYyLTdhN2U4ZTFhZGJiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwMDQwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGVlOGMxMTc1MDdlNjhmZjM1NDJmZGJmYTg5YWQ0N2JmMTI4Yjk1NmQ0MGU3Mzc4YjIzMDRlNGQ5MWVlZmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nCeKuXQ7wxzw1udaDV7LLtVy2e2RARl7a4uNj-AXqho)

Still working on this though

2024-06-21 19:25 UTC, devwilliamy commented
Bug with percentages
https://coverland-2-0-git-george-preview-low-e6619e-coverland-3615f02b.vercel.app/car-covers/premium-plus/aston-martin/rapide/2010-2017
https://www.loom.com/share/d87b9d134c624591a7c8e10947311e9f

Probably not a big deal, can look at it next iteration

2024-06-21 19:34 UTC, devwilliamy requested changes
Need to fix math logic.

Don't forget to fix in seat covers too

2024-06-21 19:34 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    const evenCartProductPrice = Number(cartProduct.price);
What is evenCartProductPrice supposed to mean? 

Like even / odd?

Or is this supposed to be the original?

2024-06-21 19:34 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +        evenCartProductPrice - Math.floor(evenCartProductPrice / 4) - 0.05;
You should not be using Math.floor here in this spot

evenCartProductPrice = 370
evenCartProductPrice / 4 = 92.5
Math.floor(evenCartProductPrice / 4) = 92

calcPrice = 277.95 instead of 277.5

Unless the Math.floor was a particular requirement from Calvin, this needs to be fixed

![image](https://github.com/devwilliamy/coverland/assets/156253900/439c4342-a4dd-45b6-bc39-1035f8cd1bd4)

2024-06-21 19:34 UTC, george-icarcover commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    const evenCartProductPrice = Number(cartProduct.price);
yea its supposed to be the original_price, will rename

2024-06-21 19:35 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +        evenCartProductPrice - Math.floor(evenCartProductPrice / 4) - 0.05;
Sorry the calculator price is supposed to be 277.45 not 277.55

![image](https://github.com/devwilliamy/coverland/assets/156253900/74de6208-4efa-4f1f-850e-37d043f64642)

2024-06-21 19:39 UTC, george-icarcover commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +        evenCartProductPrice - Math.floor(evenCartProductPrice / 4) - 0.05;
He did explicitly state that he wanted the prices to end in 0.95¢

2024-06-21 19:49 UTC, devwilliamy requested changes
Another math discrepancy

2024-06-21 19:49 UTC, devwilliamy commented on src/app/api/admin-panel/order-items/route.ts
> +    }
You should turn this into a function and re-use it between here and on the front end or vice versa

This math is the more right one

![image](https://github.com/devwilliamy/coverland/assets/156253900/ee058b13-0f48-4bd4-a6ad-88d477de4d46)

The numbers are not matching (554.9 vs 555.9)
![image](https://github.com/devwilliamy/coverland/assets/156253900/4d7e4b8c-0a57-4aad-b906-f925373bbcc2)

2024-06-21 19:57 UTC, devwilliamy commented
This is pretty minor but something to think about later

Price flickers on page load
https://www.loom.com/share/bf187d0bdaaa470b8c1be37e71100fa1

2024-06-21 20:01 UTC, george-icarcover commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +        evenCartProductPrice - Math.floor(evenCartProductPrice / 4) - 0.05;
Confirmed prices ending in 0.50¢ should stay at 0.50¢

2024-06-21 20:14 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    const evenCartProductPrice = Number(cartProduct.price);
In the future, usually variables on front end / react is camelCased

2024-06-22 00:04 UTC, devwilliamy commented on src/lib/utils/calculations.ts
> +  if (!cartProduct.msrp) return;
can be in one if

2024-06-22 00:04 UTC, devwilliamy commented on src/lib/utils.ts
> +import { TSeatCoverDataDB } from './db/seat-covers';
Do these need to be cleaned up?

2024-06-22 00:04 UTC, devwilliamy commented on src/app/(main)/[productType]/components/ProductContent.tsx
> +    checkLowQuantity();
Does this need to be await or does this even need to be async?

2024-06-22 00:09 UTC, devwilliamy commented
Confirm with Calvin if it should be .5 or .50
![image](https://github.com/devwilliamy/coverland/assets/156253900/9ce51469-8c3e-441c-8186-2b3b865c6030)

2024-06-22 00:13 UTC, george-icarcover commented
> Confirm with Calvin if it should be .5 or .50 ![image](https://private-user-images.githubusercontent.com/156253900/341913870-9ce51469-8c3e-441c-8186-2b3b865c6030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTUzODYsIm5iZiI6MTcxOTAxNTA4NiwicGF0aCI6Ii8xNTYyNTM5MDAvMzQxOTEzODcwLTljZTUxNDY5LThjM2UtNDQxYy04MTg2LTJiM2I4NjVjNjAzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwMDExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzM1OTMwMDYyNDMyYzJhMjFlOWE5NjI4MzdmZDU3MmMzNTc4ZGY0MTgwYjk5ZmVjYjNkZTBiNTg0YzVlNjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mo3GETkhq5lnl1g8brrv2uO2JfhrZ4b8CmFiC4dHRGQ)
> 
> ![image](https://private-user-images.githubusercontent.com/156253900/341913980-94cb68a3-707f-43da-ad2d-89046e051cd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTUzODYsIm5iZiI6MTcxOTAxNTA4NiwicGF0aCI6Ii8xNTYyNTM5MDAvMzQxOTEzOTgwLTk0Y2I2OGEzLTcwN2YtNDNkYS1hZDJkLTg5MDQ2ZTA1MWNkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwMDExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWM4NTcyMTM3ZDYzMmE2NDJiNzNmNDdlYjUxMDNjZThmMmJkMzcwOWJkYjc1ZDI3NTNmYzU1NmQ4YWM1NWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ndSe5ygifhPJw_uTru4hFwri-nZcf9sFJhytjlUj2cQ)

50

2024-06-22 00:13 UTC, devwilliamy approved these changes
Minor fixes left but otherwise lgtm

2024-06-22 00:18 UTC, devwilliamy commented
This installment price wrong
https://coverland-2-0-git-george-preview-low-e6619e-coverland-3615f02b.vercel.app/car-covers/premium-plus/aston-martin/rapide/2010-2017

![image](https://github.com/devwilliamy/coverland/assets/156253900/42f752fe-0c84-4513-96ac-6eda138a98f0)

2024-06-24 16:24 UTC, merged