Re-structuring checkout page
devwilliamy/coverland pull request #571
Opened 2024-06-26 23:33 UTC by george-icarcover

https://app.clickup.com/t/8688n0tqh

- Added order reviews to accordion
- Created one component for Desktop And mobile styling

2024-06-27 00:14 UTC, devwilliamy commented
Desktop Checkout

Padding too big. It's 80px here already and there's another 24px padding from below it
![image](https://github.com/devwilliamy/coverland/assets/156253900/ea0b99a2-2b20-455a-9644-638b3e2345e4)

2024-06-27 00:14 UTC, devwilliamy commented
Remove your sample data

![image](https://github.com/devwilliamy/coverland/assets/156253900/52d7e9eb-3c4d-43f9-9166-dd8ad75b9ffb)

2024-06-27 00:15 UTC, devwilliamy commented
Error messages don't match

![image](https://github.com/devwilliamy/coverland/assets/156253900/6d73d9f8-7e03-4975-9113-e84f2f11a830)

2024-06-27 00:24 UTC, devwilliamy commented
Order Review 

Font is a little big compared to the current design, but the font size was from an older Figma so I would say ask if this is a big enough problem to change.

![image](https://github.com/devwilliamy/coverland/assets/156253900/ac98acd4-ef34-4487-b9a6-b354c272736f)

2024-06-27 00:31 UTC, devwilliamy commented
Where's the 1-5 Business Days? (Figma says Fedex, remember it's supposed to be UPS)

![image](https://github.com/devwilliamy/coverland/assets/156253900/e634a950-a66a-4790-98e1-e233601296c5)

2024-06-27 00:32 UTC, devwilliamy commented
Continue to Order Review -> Continue to Review
Also needs to be on right side
Where is my CVV -> Where is my CVV?

![image](https://github.com/devwilliamy/coverland/assets/156253900/c30fff5b-3495-48f1-83ff-6f7d8b72d786)

2024-06-27 00:41 UTC, devwilliamy commented
You have to update the links on the policies in the text

![image](https://github.com/devwilliamy/coverland/assets/156253900/29c66baa-e5d6-48e5-808b-fdf00a0a04db)

2024-06-27 00:43 UTC, devwilliamy commented
On Mobile:
Box size is different
There's too much space between the box and the button

![image](https://github.com/devwilliamy/coverland/assets/156253900/abae3fc7-b7e9-4682-be1a-abaab5cc5943)

2024-06-27 00:43 UTC, devwilliamy commented
Billing Details State is missing

![image](https://github.com/devwilliamy/coverland/assets/156253900/0ef4397d-1eb2-46df-9629-d576e3ffc78e)

2024-06-27 00:44 UTC, devwilliamy commented
Price missing from Order Item

Submit Payment Button smaller than in Figma

![image](https://github.com/devwilliamy/coverland/assets/156253900/295536c7-110c-406b-8b54-e5266288b941)

2024-06-27 00:49 UTC, devwilliamy commented
# ‼️ You cannot store the phone numbers like this ‼️ 
It is important to be in e.164 format for google conversion API
This is an example of e.164 format: +16267368476

I know paypal isn't doing it right so I'll take a look into that but at the least you cannot break it for Stripe

**Please** check your changes and see what you took out from my code

You'll probably use this

```
      const formattedPhoneNumber =
        parsePhoneNumberFromString(phoneNumber)?.format('E.164');
```

![image](https://github.com/devwilliamy/coverland/assets/156253900/d0afdb2e-99aa-45cc-8dec-07dd65358d6c)

2024-07-01 18:21 UTC, george-icarcover commented
> Continue to Order Review -> Continue to Review Also needs to be on right side Where is my CVV -> Where is my CVV?
> 
> ![image](https://private-user-images.githubusercontent.com/156253900/343586799-c30fff5b-3495-48f1-83ff-6f7d8b72d786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTYzODgsIm5iZiI6MTcxOTg1NjA4OCwicGF0aCI6Ii8xNTYyNTM5MDAvMzQzNTg2Nzk5LWMzMGZmZjViLTM0OTUtNDhmMS04M2ZmLTZmN2Q4YjcyZDc4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQxNzQ4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWRkMGU5ZmQzNDgxMGJlYTRhYzJmMmNiODZjZGU2ODRiMWQ2OTNmZjAzZGUwYTFmOTBhYjE3NDE1ODUzYWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ErXGMt-Nfs8y8kDxntvnwrLHrMvC667pVPi5eNvTlvA)

![image](https://github.com/devwilliamy/coverland/assets/156227633/3e416d5e-181e-4856-8bca-f8f974e09d46)

2024-07-03 23:21 UTC, coverlandjohnlee commented
Step 1 Checkout Form from Figma not integrated:

![image](https://github.com/devwilliamy/coverland/assets/171850605/26d7c38f-12bb-41f5-8606-1948a9230c13)

2024-07-03 23:28 UTC, coverlandjohnlee commented
Checkout Button looks slightly different from the Figma

Figma:

![Screenshot 2024-07-03 162550](https://github.com/devwilliamy/coverland/assets/171850605/db579550-7020-49bc-8064-4b7daccfa3c3)

Page:

![Screenshot 2024-07-03 162644](https://github.com/devwilliamy/coverland/assets/171850605/4534d1f6-26f3-4865-988d-7b0d022018ef)

2024-07-03 23:32 UTC, coverlandjohnlee commented
cool checker

![image](https://github.com/devwilliamy/coverland/assets/171850605/8417b5ab-bac1-4ee2-b380-a9ea5673e142)

2024-07-03 23:42 UTC, coverlandjohnlee commented
https://github.com/devwilliamy/coverland/assets/171850605/01e95d91-ca92-441c-9d8f-2c34bc1e158d

on open and close dropdown - auto fills to place holders

2024-07-03 23:46 UTC, coverlandjohnlee commented
![image](https://github.com/devwilliamy/coverland/assets/171850605/f54f106e-d57c-4d62-9a0c-dbeab4fa60ec)

Footer is missing during checkout

2024-07-03 23:50 UTC, coverlandjohnlee commented
"Where is my cvv?" popover location different from Figma:

Page:

![Screenshot 2024-07-03 164915](https://github.com/devwilliamy/coverland/assets/171850605/acde4071-4ba9-4805-ad1a-37aa30afdd4a)

Figma:

![Screenshot 2024-07-03 164932](https://github.com/devwilliamy/coverland/assets/171850605/c545e63a-708c-4a4d-9111-e9f30a7ceca7)

2024-07-03 23:52 UTC, coverlandjohnlee commented
This is such a big change to checkouts, I'm surprised it's all in one branch. Looks pretty good overall.

2024-07-05 17:09 UTC, coverlandjohnlee commented
![image](https://github.com/devwilliamy/coverland/assets/171850605/0ad40b78-9fab-4450-96ce-ad43a6ef503b)

LGTM

2024-07-05 17:16 UTC, coverlandjohnlee commented
> https://app.clickup.com/t/8688n0tqh
> 
> * Added order reviews to accordion
> * Created one component for Desktop And mobile styling
> 
> https://www.figma.com/design/f0PiJaMbj3moDGXq45iAA1/Coverland-Website-Design?node-id=4044-52355&t=dGXRqu81bOwhM1OW-1

If you could list more newly added/changed features here it would make it more clear. Like form validation, using Zot, adding new CustomTextField with custom states etc. This is a big one a lot going on inside the new Checkout

2024-07-05 17:17 UTC, coverlandjohnlee commented
Overall, looks solid to me.

2024-07-05 17:18 UTC, coverlandjohnlee approved these changes

2024-07-05 17:18 UTC, coverlandjohnlee commented on src/components/checkout/CheckoutAccordion.tsx
> +      });
yay!! I'm glad my email code made it. I'm sorry if it was a pain to copy over. A lot of the payment related functions should ideally be more easily imported. Nothing to do with your PR though

2024-07-05 17:18 UTC, coverlandjohnlee commented on src/components/checkout/NewCheckout.tsx
> +  const {
Is there a better name than NewCheckout?

2024-07-05 17:25 UTC, george-icarcover commented
> ![image](https://private-user-images.githubusercontent.com/171850605/345648051-f54f106e-d57c-4d62-9a0c-dbeab4fa60ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDA1ODUsIm5iZiI6MTcyMDIwMDI4NSwicGF0aCI6Ii8xNzE4NTA2MDUvMzQ1NjQ4MDUxLWY1NGYxMDZlLWQ1N2MtNGQ2Mi05YTBjLWRiZWFiNGZhNjBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzI0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGM0ZTQ4Zjk4MjM5ZDhlNzgxOWE0NjQ1ODIzNGI1MDJmNTQxYmZmNzE2NGQ3NzhkODI1NmRmNTgzMTI3OTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xm5xYCQBNOPMt_iir0AFAtBImHtrAfLvupI5sQDtoX8)
> 
> Footer is missing during checkout

There should be no footer in the checkout, the no footer layout is also on the live version of our website

2024-07-05 17:43 UTC, george-icarcover commented on src/components/checkout/CustomTextField.tsx
> +        };
Yep. 
When the user clicks away from the element, it loses focus,
When it loses focus `onBlur()` is called

2024-07-05 17:44 UTC, george-icarcover commented on src/components/checkout/CustomTextField.tsx
> +      setShippingState((prevState) => {
Def not intentional, they should be showing the error if there is one.

2024-07-05 17:48 UTC, george-icarcover commented on src/components/checkout/AddressForm.tsx
> +  | 'postal_code'
Yea, stripe expects these naming conventions and we are using the naming conventions to map through object keys.

2024-07-05 17:48 UTC, coverlandjohnlee commented
Mobile: (I used my iphone 12 & Safari)
Card / Google Pay are good.

Apple pay I got stuck here:
![unnamed (3)](https://github.com/devwilliamy/coverland/assets/171850605/63482238-3891-46e0-bd5a-f444aec542a4)

Paypal when I click Pay with PayPal nothing happened:
![unnamed (2)](https://github.com/devwilliamy/coverland/assets/171850605/fb590527-6f6b-4017-9025-09c2469a819a)

2024-07-05 17:49 UTC, coverlandjohnlee commented
When I sign in on my coverland.com account and go to checkouts. It would be nice if it autofilled like name / email etc. Maybe for a next version?:
![unnamed](https://github.com/devwilliamy/coverland/assets/171850605/78bb187b-4eb2-4cd4-8d84-e76ffc883b8f)

Here I just changed my email input field:
![unnamed (1)](https://github.com/devwilliamy/coverland/assets/171850605/2d3bd8cb-2626-4cbf-859d-e1507ad5fadb)

2024-07-05 17:53 UTC, george-icarcover commented
> When I sign in on my coverland.com account and go to checkouts. It would be nice if it autofilled like name / email etc. Maybe for a next version?: ![unnamed](https://private-user-images.githubusercontent.com/171850605/346195805-78bb187b-4eb2-4cd4-8d84-e76ffc883b8f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDIyNjMsIm5iZiI6MTcyMDIwMTk2MywicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1ODA1LTc4YmIxODdiLTRlYjItNGNkNC04ZDg0LWU3NmZmYzg4M2I4Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzUyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWZjYmEwMWQzY2Y3NDZjMjZiMGM1ZjVkMGM1MzdmNzY5MzI2NjFlOTNkY2I5M2MyN2NkNGJiMmY3Yzk0NDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dxy51oPdJzs-K411k1zQlA5xf1uer5VX-q1GyVdpwl8)
> 
> Here I just changed my email input field: ![unnamed (1)](https://private-user-images.githubusercontent.com/171850605/346195886-2d3bd8cb-2626-4cbf-859d-e1507ad5fadb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDIyNjMsIm5iZiI6MTcyMDIwMTk2MywicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1ODg2LTJkM2JkOGNiLTI2MjYtNGNiZi04NTlkLWUxNTA3YWQ1ZmFkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzUyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWI1NWNjMTM5Y2JkMzdjMTc5OTIxMjgwMTJhNDdmZTI1MWI0M2I0ZWNkZDc0NTBjMjcxZDAxNWQ2MjgwNjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2DLPajiU8qIbCrHplimPCJlOzY75UU8b2I8D5IbKfmo)
> 
 Sorry I forgot to remove this autofill from this version, it wont be pushed to the live versions

2024-07-05 17:55 UTC, george-icarcover commented on src/components/checkout/AddressForm.tsx
>      }
Yea, I could probably check if the field is not visited before as well, I will try to make this clearer

2024-07-05 18:00 UTC, george-icarcover commented on src/components/checkout/AddressForm.tsx
>    phoneNumber: z.string().refine(
That form schema should not be in the codebase anymore, I will clean it up.

The email field should be displaying its errors

2024-07-05 19:46 UTC, george-icarcover commented on src/components/checkout/NewCheckout.tsx
> +  const {
Renamed to `CreditCardSection`

2024-07-05 19:48 UTC, george-icarcover commented
> Mobile: (I used my iphone 12 & Safari) Card / Google Pay are good.
> 
> Apple pay I got stuck here: ![unnamed (3)](https://private-user-images.githubusercontent.com/171850605/346195389-63482238-3891-46e0-bd5a-f444aec542a4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDkxODMsIm5iZiI6MTcyMDIwODg4MywicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1Mzg5LTYzNDgyMjM4LTM4OTEtNDZlMC1iZDVhLWY0NDRhZWM1NDJhNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxOTQ4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTgwN2YwYWEyNDQ2NjI0YzczNWIwMjMyMTJhYTIzNTYzMDM5OWFkN2NjMzBiODdjZmY2ZDllNzZlYzc4MjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZSJqomPWv4HBwMjo67de8swmr8CvnxfiSGDovH1lbSU)
> 
> Paypal when I click Pay with PayPal nothing happened: ![unnamed (2)](https://private-user-images.githubusercontent.com/171850605/346195554-fb590527-6f6b-4017-9025-09c2469a819a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDkxODMsIm5iZiI6MTcyMDIwODg4MywicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1NTU0LWZiNTkwNTI3LTZmNmItNDAxNy05MDI1LTA5YzI0NjlhODE5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxOTQ4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTViNzA4NGYzNGQ0ZjU2NzAxMDU5ODNiN2YxMTUwMzA5MGNiNWNjYTQwZTA5ZGJkOWU4ODI1NTQzZjk4YjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wmlleeUFJz3_HlHbB-OAe68fkvVGOLhkq8Q4-ezJeo0)

Google Pay and Apple pay should not be showing here, will remove

2024-07-05 19:51 UTC, george-icarcover commented
> When I sign in on my coverland.com account and go to checkouts. It would be nice if it autofilled like name / email etc. Maybe for a next version?: ![unnamed](https://private-user-images.githubusercontent.com/171850605/346195805-78bb187b-4eb2-4cd4-8d84-e76ffc883b8f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDIyOTksIm5iZiI6MTcyMDIwMTk5OSwicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1ODA1LTc4YmIxODdiLTRlYjItNGNkNC04ZDg0LWU3NmZmYzg4M2I4Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGMwZWZhNGJlNzE4ZGYyNDU4MjI3ZDllZTk5MDk4YzViNTljNjlhZTI2ZjYwNDJiYzg4N2ViNTQwMDQzNWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPwiJWFKHZHBoN8js2Rvb2CrP8NsMXmVJw9BWmlPDBs)
> 
> Here I just changed my email input field: ![unnamed (1)](https://private-user-images.githubusercontent.com/171850605/346195886-2d3bd8cb-2626-4cbf-859d-e1507ad5fadb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDIyOTksIm5iZiI6MTcyMDIwMTk5OSwicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1ODg2LTJkM2JkOGNiLTI2MjYtNGNiZi04NTlkLWUxNTA3YWQ1ZmFkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2E1OTMyMWRlMTNlNzRiMDRhYWU0ZTA3ZDBjMzk0NTVlNzJhYThjMTNlNjk5ZDQyNmQyODI2ZGEzZTAzM2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fsUFH8D2zQzDujayL7W2wWxgWmKbOmxk0o643zLfPq0)

We'll ask if this is something that needs to be prioritized, if not, I will not be working on it.

It sounds like a good quality of life change

2024-07-05 19:53 UTC, george-icarcover commented on src/app/api/stripe/payment-intent/route.ts
> +
It's all stripe, payment intents come from stripe nd the payment methods are what is marked here.

Klarna is commented out because we have disabled the Klarna payment option on the stripe dashboard. 

We will be adding it back later when integrating Klarna in a different branch.

2024-07-06 00:39 UTC, devwilliamy commented
> > When I sign in on my coverland.com account and go to checkouts. It would be nice if it autofilled like name / email etc. Maybe for a next version?: ![unnamed](https://private-user-images.githubusercontent.com/171850605/346195805-78bb187b-4eb2-4cd4-8d84-e76ffc883b8f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDIyOTksIm5iZiI6MTcyMDIwMTk5OSwicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1ODA1LTc4YmIxODdiLTRlYjItNGNkNC04ZDg0LWU3NmZmYzg4M2I4Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGMwZWZhNGJlNzE4ZGYyNDU4MjI3ZDllZTk5MDk4YzViNTljNjlhZTI2ZjYwNDJiYzg4N2ViNTQwMDQzNWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPwiJWFKHZHBoN8js2Rvb2CrP8NsMXmVJw9BWmlPDBs)
> > Here I just changed my email input field: ![unnamed (1)](https://private-user-images.githubusercontent.com/171850605/346195886-2d3bd8cb-2626-4cbf-859d-e1507ad5fadb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDIyOTksIm5iZiI6MTcyMDIwMTk5OSwicGF0aCI6Ii8xNzE4NTA2MDUvMzQ2MTk1ODg2LTJkM2JkOGNiLTI2MjYtNGNiZi04NTlkLWUxNTA3YWQ1ZmFkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2E1OTMyMWRlMTNlNzRiMDRhYWU0ZTA3ZDBjMzk0NTVlNzJhYThjMTNlNjk5ZDQyNmQyODI2ZGEzZTAzM2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fsUFH8D2zQzDujayL7W2wWxgWmKbOmxk0o643zLfPq0)
> 
> We'll ask if this is something that needs to be prioritized, if not, I will not be working on it.
> 
> It sounds like a good quality of life change

Would be a good quality of life change yes, but isn't a priority at the moment and should not be part of this PR. Can bring it up to Calvin and see what he thinks.

2024-07-06 00:43 UTC, devwilliamy commented
> > ![image](https://private-user-images.githubusercontent.com/171850605/345648051-f54f106e-d57c-4d62-9a0c-dbeab4fa60ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDA1ODUsIm5iZiI6MTcyMDIwMDI4NSwicGF0aCI6Ii8xNzE4NTA2MDUvMzQ1NjQ4MDUxLWY1NGYxMDZlLWQ1N2MtNGQ2Mi05YTBjLWRiZWFiNGZhNjBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzI0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGM0ZTQ4Zjk4MjM5ZDhlNzgxOWE0NjQ1ODIzNGI1MDJmNTQxYmZmNzE2NGQ3NzhkODI1NmRmNTgzMTI3OTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xm5xYCQBNOPMt_iir0AFAtBImHtrAfLvupI5sQDtoX8)
> > Footer is missing during checkout
> 
> There should be no footer in the checkout, the no footer layout is also on the live version of our website

Looking at the Figma I do notice it there.
I don't know if Ashley unintentionally added it there.

Can you double check with Calvin if we want to continue to not have the footer in check out? If he wants it back in, that should be another task.

2024-07-06 02:04 UTC, devwilliamy reviewed
Reviewed the code.
There are some components are a little confusing because of the size but this has been going on for too long so I'm willing to overlook it for now.
Still need to review the actual implementation though

2024-07-06 02:04 UTC, devwilliamy commented on src/components/checkout/PaymentSelector.tsx
>    selectedPaymentMethod,
I'm confused what is this component for? Is it supposed to be used in Payment Selector?

2024-07-06 02:06 UTC, devwilliamy commented
Not enough spacing between cart and the banner

![image](https://github.com/devwilliamy/coverland/assets/156253900/1885481f-4d93-4e4a-ba6c-f591c2047761)

2024-07-06 02:07 UTC, devwilliamy commented
On desktop, need more space between save & continue and the line

![image](https://github.com/devwilliamy/coverland/assets/156253900/21b6a63c-c267-441b-a3b3-42b445ff07d1)

2024-07-06 02:15 UTC, devwilliamy commented
I don't think billing should have different name, should it? 
![image](https://github.com/devwilliamy/coverland/assets/156253900/eb22c2b0-bad5-414b-abc1-602b502675de)

2024-07-06 02:17 UTC, devwilliamy commented
When I click on edit for shipping, it should re-populate the address

![image](https://github.com/devwilliamy/coverland/assets/156253900/d85a79ba-6e49-447d-b7a1-d1872cf465fe)

2024-07-06 02:18 UTC, devwilliamy commented
I autopopulated the fields but save and continue is grayed out what's going on?

![image](https://github.com/devwilliamy/coverland/assets/156253900/12875084-b96b-4aa2-8994-9cd2cd15fdca)

2024-07-06 02:21 UTC, devwilliamy commented
> You have to update the links on the policies in the text
> 
> ![image](https://private-user-images.githubusercontent.com/156253900/343586897-29c66baa-e5d6-48e5-808b-fdf00a0a04db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzE3NjMsIm5iZiI6MTcyMDIzMTQ2MywicGF0aCI6Ii8xNTYyNTM5MDAvMzQzNTg2ODk3LTI5YzY2YmFhLWU1ZDYtNDhlNS04MDhiLWZkZjAwYTBhMDRkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQwMjA0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGNmZDViMmMyOTQwZTQ3OTUxY2VjNDg1Nzc4NWNmYjEwODkyZTU3NzdkYmNkYzBkYjJjZjczZDU5YTkyNGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rq187RkVJQyo12eH-wfpGleQ5HQ8XnQ2cfYCh0F3txo)

You thumbs up'd this comment but it's still not fixed, what happened?

![image](https://github.com/devwilliamy/coverland/assets/156253900/f09c7a99-1da1-49f4-b9a8-c1709fd1e33f)

2024-07-06 03:36 UTC, devwilliamy commented
When a card has a problem, you need to reset the loading state for the submit payment, because it's stuck like that even when a user goes back to change it.

![image](https://github.com/devwilliamy/coverland/assets/156253900/1522be30-33df-4969-88c5-47a28dce16d8)

2024-07-06 03:49 UTC, devwilliamy reviewed
I would bring it up to Calvin but it's a pretty bad user experience when a user tries to auto fill and you still can't continue on.

Stop using prefilled data unless you're sure the behavior is working as intended otherwise you'll miss these kinds of issues.

2024-07-06 03:49 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +import { getTotalDiscountPrice } from '@/lib/utils/calculations';
This is not the right `getTotalDiscountPrice` that you should be using.

You should be using the one from the context. I'm frankly surprised it's still working even if this is returning undefined

2024-07-06 03:49 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +        phone_number: shippingAddress.phone || '',
This phone number needs to be e.164 format

2024-07-06 03:49 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +          ph: [hashData(shippingAddress.phone || '')],
this also needs to be e.164

2024-07-06 03:49 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +    if (process.env.NEXT_PUBLIC_IS_PREVIEW !== 'PREVIEW') {
Can you just convert the phone number to e.164 at the beginning of this if statement and use that for all the conversion phone numbers?

2024-07-06 03:56 UTC, devwilliamy requested changes
I personally don't think it should go out with the auto fill issue and the phone number issue for conversion APIs. But if this is necessary to go out, I'll forgo it and we'll see what happens

2024-07-08 16:55 UTC, george-icarcover commented on src/components/checkout/CheckoutAccordion.tsx
> +          amount: 888888,
Sorry I left a lot of stray code in

2024-07-08 17:31 UTC, george-icarcover commented on src/components/checkout/AddressForm.tsx
> +  // useEffect(() => {
The phone number or the use efffect?

2024-07-08 17:33 UTC, george-icarcover commented on src/components/checkout/CheckoutAccordion.tsx
> +  const handleGetTax = async () => {
Removing

2024-07-08 17:35 UTC, george-icarcover commented on src/components/checkout/CheckoutAccordion.tsx
> +    }
Removing tax from this area, will handle this in taxjar implementation

2024-07-08 17:36 UTC, george-icarcover commented on src/components/checkout/CheckoutAccordion.tsx
> +    }
removing from here, I will fix in #589

2024-07-08 18:03 UTC, george-icarcover commented on src/components/checkout/CheckoutAccordion.tsx
> +        phone_number: shippingAddress.phone || '',
Weird, I am updating the customer info on submit, this should have been in the correct format, where can I go to check the conversion output?

2024-07-08 18:38 UTC, george-icarcover commented on src/components/checkout/PaymentSelector.tsx
>    selectedPaymentMethod,
This is the payment selector component

2024-07-08 18:57 UTC, george-icarcover commented
> > You have to update the links on the policies in the text
> > ![image](https://private-user-images.githubusercontent.com/156253900/343586897-29c66baa-e5d6-48e5-808b-fdf00a0a04db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzE3NjMsIm5iZiI6MTcyMDIzMTQ2MywicGF0aCI6Ii8xNTYyNTM5MDAvMzQzNTg2ODk3LTI5YzY2YmFhLWU1ZDYtNDhlNS04MDhiLWZkZjAwYTBhMDRkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQwMjA0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGNmZDViMmMyOTQwZTQ3OTUxY2VjNDg1Nzc4NWNmYjEwODkyZTU3NzdkYmNkYzBkYjJjZjczZDU5YTkyNGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rq187RkVJQyo12eH-wfpGleQ5HQ8XnQ2cfYCh0F3txo)
> 
> You thumbs up'd this comment but it's still not fixed, what happened?
> 
> ![image](https://private-user-images.githubusercontent.com/156253900/346246740-f09c7a99-1da1-49f4-b9a8-c1709fd1e33f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NjMzODQsIm5iZiI6MTcyMDQ2MzA4NCwicGF0aCI6Ii8xNTYyNTM5MDAvMzQ2MjQ2NzQwLWYwOWM3YTk5LTFkYTEtNDlmNC1iOWE4LWMxNzA5ZmQxZTMzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxODI0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmE1YzY2YmUwYWMxMTkyYjZhOWNhNmQ4NjY0YTE0MGMwM2Q4YWUyMmNjYWVhYjVlMDcwZWI0OTQ3M2QwOTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bB3vVpjt2THZjKPUQ19ypyzfblcd_OOhSF-dcaaW_wk)

I have 2 different areas with this code, I will extract to a element so I only have to change in 1 place

2024-07-08 19:31 UTC, george-icarcover commented
> > > ![image](https://private-user-images.githubusercontent.com/171850605/345648051-f54f106e-d57c-4d62-9a0c-dbeab4fa60ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDA1ODUsIm5iZiI6MTcyMDIwMDI4NSwicGF0aCI6Ii8xNzE4NTA2MDUvMzQ1NjQ4MDUxLWY1NGYxMDZlLWQ1N2MtNGQ2Mi05YTBjLWRiZWFiNGZhNjBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzI0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGM0ZTQ4Zjk4MjM5ZDhlNzgxOWE0NjQ1ODIzNGI1MDJmNTQxYmZmNzE2NGQ3NzhkODI1NmRmNTgzMTI3OTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xm5xYCQBNOPMt_iir0AFAtBImHtrAfLvupI5sQDtoX8)
> > > Footer is missing during checkout
> > 
> > 
> > There should be no footer in the checkout, the no footer layout is also on the live version of our website
> 
> Looking at the Figma I do notice it there. I don't know if Ashley unintentionally added it there.
> 
> Can you double check with Calvin if we want to continue to not have the footer in check out? If he wants it back in, that should be another task.

Confirmed No footer

2024-07-08 19:36 UTC, george-icarcover commented on src/components/checkout/CustomTextField.tsx
> +      {type !== 'state' && type !== 'phoneNumber' && type !== 'postal_code' && (
There is a type property being passed in to every CustomTextField, if the type is not one of those types it shows the default CustomTextField. 

State, Phone Number, and Postal Code all have a unique implementation in CustomTextFields

2024-07-09 02:05 UTC, devwilliamy commented on src/components/checkout/CustomTextField.tsx
> +      {type !== 'state' && type !== 'phoneNumber' && type !== 'postal_code' && (
Right, and because they have those unique implementations, I feel like those (in the future, or for similar implementations in the future) be extracted into their own component instead of making this one component larger

2024-07-09 02:06 UTC, devwilliamy commented on src/components/checkout/PaymentSelector.tsx
>    selectedPaymentMethod,
Sorry I meant to say in the Payment component.
Looks like there's some re-used code in both of these

2024-07-09 23:19 UTC, devwilliamy commented
Summary too close to the border

![image](https://github.com/devwilliamy/coverland/assets/156253900/5007d88a-3e71-4f72-b9ae-3d43676c0379)

2024-07-09 23:28 UTC, devwilliamy commented
When I tried using this phone number:

+6 (127) 384-7592

It got saved like this:
+161273847592

Maybe it won't be a problem since we're not doing international yet? But this might be a problem later

2024-07-09 23:30 UTC, devwilliamy requested changes
Formatted phone isn't working.
Some design fixes
Paypal isn't working as well.

2024-07-09 23:30 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +    )?.format('E.164');
Did you check to see if this would work?

I'm currently getting this:
```
formattedPhone
: 
undefined
ogPhone
: 
"(626) 736-8476"
```

2024-07-09 23:48 UTC, george-icarcover commented on src/components/checkout/CheckoutAccordion.tsx
> +    )?.format('E.164');
I tested it in the `mapPaymentIntentAndMethodToOrder` area, but I guess I forgot the 'US', which is weird becayse they aren't requiring a country in the documentation.

Also I think me setting it to 'US' is causing the +1 to appear.

2024-07-11 02:22 UTC, devwilliamy reviewed
Phone number is still not e.164 format

I personally think you should be relying on the `libphonenumber-js` library a bit more. It's doing everything that you're trying to do, but better. It's tested and it's proven to work because people use it.

I would also recommend you just keep the raw string that the user inputs, but you use the library to DISPLAY whatever format you want. This will save you the trouble of having clean the phone number.

However, since we are trying to just get this out, make the `num.replaceAll` fix. 

Also, I'm not sure where in your code you're updating the phone number, I don't know if that's intentional (my input was (626) 736-8476)

![image](https://github.com/devwilliamy/coverland/assets/156253900/dcf3ad76-8d10-4fa4-a733-4c4338ccbba6)

2024-07-11 02:22 UTC, devwilliamy commented on src/components/checkout/CustomTextField.tsx
> +  };
I'm wondering why aren't you just using `libphonenumber-js` to validate the phone number? 

These two lines that I had previously would check if the phone number is possible. Was there something wrong with it? Was there a combination of phone number that broke it?
```
      const phoneNumber = parsePhoneNumberFromString(value, 'US');
      return phoneNumber && phoneNumber.isPossible();
```

2024-07-11 02:22 UTC, devwilliamy commented on src/components/checkout/CustomTextField.tsx
> +  };
If you are trying to format it to look like this (###) ###-####, that's fine. You can use this from the library:
```
  const phoneNumber = parsePhoneNumberFromString(input, 'US'); // This input should just be numbers
  const formattedNumber = phoneNumber.formatNational();
  console.log(formattedNumber); // (626) 736-8476
```

Here's an example object that `phoneNumber` will be:
```
{
    "country": "US",
    "countryCallingCode": "1",
    "nationalNumber": "6267368476",
    "number": "+16267368476"
}
```

Therefor if you need e.164, you can do like this:
```
const e164Number = phoneNumber.number;
console.log(e164Number); // +16267368476
```


Looking at this closer, why is this a valid phone number? There's no area code. Please let me know why you have this here and if I'm missing something.
```
   if (cleaned.length === 7) {
      match = cleaned.match(/^(\d{3})(\d{4})$/);
      if (match) {
        return `${match[1]}-${match[2]}`;
      }
```

This will also be a problem later down the line (something you don't 'have to worry about right now but wouldn't have to worry in general if you used the library is this only works for US-Canada numbers. Once again, this is fine for now because it's all we're using but if someone doesn't have. US/CA number they can't

```
      match = cleaned.match(/^(\d{1})(\d{3})(\d{3})(\d{4})$/);
```


Have the library do the heavy lifting for you. Stop trying to re-do what the library already does for you and is tested and proven to work.

2024-07-11 02:22 UTC, devwilliamy commented on src/lib/utils.ts
> +};
Your num.replaceAll isn't doing anything
And so instead of returning the right format, it's returning +6267368476

This is not e.164 format

2024-07-11 02:22 UTC, devwilliamy requested changes
Requesting Phone Number changes.

Haven't checked Paypal yet

2024-07-12 19:03 UTC, devwilliamy commented on src/components/checkout/Payment.tsx
> -      )}
Put this message, paypalsuccessmessage, and error message back in

2024-07-12 20:41 UTC, coverlandjohnlee commented
![image](https://github.com/user-attachments/assets/77196c82-23ad-416b-b8a3-7aea4f373fcc)

Wowza preorder -> email merged great thank you!

2024-07-13 00:09 UTC, devwilliamy commented
Low priority but something to note is you might not have other card images (tried using amex)

<img width="694" alt="image" src="https://github.com/user-attachments/assets/69624d31-0b2d-4e10-b73e-47ce6a37442a">

2024-07-15 18:09 UTC, merged