Payment Accordion to include Order Details
devwilliamy/coverland pull request #588
Opened 2024-07-02 23:19 UTC by george-icarcover

George/preview updating payment accordion to contain order review

2024-07-10 01:21 UTC, devwilliamy reviewed
Had a few comments, but mainly concerned about the merge so can you double check things are okay once you merge preview checkout design changes into this branch?

2024-07-10 01:21 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +                          <div className="relative flex w-full items-center justify-center  py-4 ">
Can you make sure to update your branch with preview-checkout-design-changes to make sure this uses that Terms component you made?

2024-07-10 01:21 UTC, devwilliamy commented on src/components/checkout/AddressForm.tsx
> -  // };
Hopefully when we merge stuff in this doesn't make github think we want to remove this

2024-07-10 01:21 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +                            await handleSubmit();
Does this need to be async await?

2024-07-10 01:21 UTC, devwilliamy commented on src/components/checkout/NewCheckout.tsx
>  import {
Did you rename this in the other PR? Make sure github doesn't think this is a separate file

2024-07-10 23:42 UTC, george-icarcover commented on src/components/checkout/AddressForm.tsx
> -  // };
I removed it, it should be ok, it is in the Autocomplete branch

2024-07-10 23:49 UTC, george-icarcover commented on src/components/checkout/CheckoutAccordion.tsx
> +                          <div className="relative flex w-full items-center justify-center  py-4 ">
Shouldn't I update this one after #571 is done?

2024-07-11 00:19 UTC, george-icarcover commented on src/components/checkout/NewCheckout.tsx
>  import {
Yep `NewCheckout` to `CreditCardSection`

2024-07-12 17:25 UTC, devwilliamy commented
Paypal buttons are too long and also go over order details

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/0417c0b6-593a-46ef-83ee-18e0b171ed85">

<img width="448" alt="image" src="https://github.com/user-attachments/assets/1ec54652-71fb-4059-bb96-29682c952322">

2024-07-12 17:42 UTC, devwilliamy commented
Why does it say ur card security is incomplete here?

<img width="643" alt="image" src="https://github.com/user-attachments/assets/c6b9df57-2b94-4d70-82a0-8af7d13ddf53">

2024-07-12 18:12 UTC, devwilliamy commented
It seems like you're not returning an error if this is not a legit phone number

<img width="714" alt="image" src="https://github.com/user-attachments/assets/dcb5e375-dd80-43c5-96a0-1bdcf6e586b6">

Because it looks like it'll format if it's a good number

<img width="701" alt="image" src="https://github.com/user-attachments/assets/876f47a5-64b2-49d0-9b75-467206ded399">

Maybe not the most important but if you have time, would be helpful to see

2024-07-12 18:13 UTC, devwilliamy commented
You should really look into putting the messages back for submit payment and for paypal

I tried using a card that should be declined but I didn't get an error message saying why it failed.

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/7a1738e9-141e-4447-b9fb-b5204854ccb1">

2024-07-12 18:19 UTC, devwilliamy requested changes
For the Paypal console logs, can just comment out since they're being used a lot.

Please clean up other unneeded comment (leave a comment to why you're leaving it if you are) 
Clean up console logs (unless you're leaving for a reason)

I think the error messages should go back in for payment because we've had complains before of people not knowing why their payment isn't going through. Also important for paypal for the success message to show because customers often double pay through paypal.

Also think we don't need paypal to save billing

2024-07-12 18:42 UTC, devwilliamy commented on src/components/checkout/CreditCardSection.tsx
> +
This can't be here because it's after an if statement.
What are you trying to do with this useEffect?

2024-07-19 16:50 UTC, closed without merging