Checkout Page - Taxjar Implementation
devwilliamy/coverland pull request #589
Opened 2024-07-03 16:44 UTC by george-icarcover

- Make sure tax is calculated after shipping details have been obtained
- Make sure payment routes also show the correct total with tax

2024-07-10 01:32 UTC, devwilliamy requested changes
There are some paypal changes that should be in here but are being removed

2024-07-10 01:32 UTC, devwilliamy commented on src/app/(noFooter)/checkout/utils/index.ts
> +    console.error(err);
Why is the error being removed? Should keep this as is

2024-07-10 01:32 UTC, devwilliamy commented on src/components/checkout/CheckoutAccordion.tsx
> +    console.log({ amount_to_collect, totalWithTax, taxSum, taxRes });
Remove console logs throughout these PR please

2024-07-10 01:32 UTC, devwilliamy commented on src/components/checkout/PayPalButtonSection.tsx
> -    useCheckoutContext();
Somethings not right, why are these removed?

2024-07-10 01:32 UTC, devwilliamy commented on src/components/checkout/PayPalButtonSection.tsx
> -          }}
This should be in here and not deleted i'm not sure why this is getting taken out

2024-07-10 01:32 UTC, devwilliamy commented on src/components/checkout/PayPalButtonSection.tsx
> -            }
This should be in here

2024-07-10 01:32 UTC, devwilliamy commented on src/components/checkout/PayPalButtonSection.tsx
> -              );
This should be in here

2024-07-10 01:37 UTC, devwilliamy commented
I wasn't able to continue to order review.

Tax is also not showing up..? Not sure where this is supposed to be populated

![image](https://github.com/devwilliamy/coverland/assets/156253900/42bf4092-a51e-4d6e-9744-adf8d74eec65)

2024-07-10 17:16 UTC, george-icarcover commented
> I wasn't able to continue to order review.
> 
> Tax is also not showing up..? Not sure where this is supposed to be populated
> 
> ![image](https://private-user-images.githubusercontent.com/156253900/347228767-42bf4092-a51e-4d6e-9744-adf8d74eec65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzE5NTksIm5iZiI6MTcyMDYzMTY1OSwicGF0aCI6Ii8xNTYyNTM5MDAvMzQ3MjI4NzY3LTQyYmY0MDkyLWE1MWUtNGQ2ZS05NzQ0LWFkZjhkNzRlZWM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxNzE0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODk3ZGRkMmFiZGI0MDZmNzZmOGJkMzg1YTJlYzAzMmNhNTU4MDhlODFjMzk5YTRhYWRkZTA5M2M5ZDQ0ZTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5SZabD6vJnMDLFsUtfBNjoztBzi6a-BS8g3AXlWwgHY)

If this is before the shipping details have been saved, it will not calculate tax as the taxjar api requires country, state, and zipcode

2024-07-15 20:52 UTC, devwilliamy commented
> > I wasn't able to continue to order review.
> > Tax is also not showing up..? Not sure where this is supposed to be populated
> > ![image](https://private-user-images.githubusercontent.com/156253900/347228767-42bf4092-a51e-4d6e-9744-adf8d74eec65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzE5NTksIm5iZiI6MTcyMDYzMTY1OSwicGF0aCI6Ii8xNTYyNTM5MDAvMzQ3MjI4NzY3LTQyYmY0MDkyLWE1MWUtNGQ2ZS05NzQ0LWFkZjhkNzRlZWM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxNzE0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODk3ZGRkMmFiZGI0MDZmNzZmOGJkMzg1YTJlYzAzMmNhNTU4MDhlODFjMzk5YTRhYWRkZTA5M2M5ZDQ0ZTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5SZabD6vJnMDLFsUtfBNjoztBzi6a-BS8g3AXlWwgHY)
> 
> If this is before the shipping details have been saved, it will not calculate tax as the taxjar api requires country, state, and zipcode

This is at the very end 

![image](https://github.com/user-attachments/assets/c90a42bd-7f92-4b32-8019-dd4f0e66abc6)

2024-07-15 21:09 UTC, devwilliamy reviewed
I'll need to look at the code again once you've merged in preview again

Something I'm wondering about is logging the tax in the orders table
 
If each item has a tax amount on it, then will need to track in order items table too, but if it's just a tax on the whole order, probably just need a column in the _Orders table to make sure the total amount makes sense with the discounts and other prices

2024-07-19 16:50 UTC, closed without merging

2024-08-23 20:00 UTC, devwilliamy commented
Completed in 
Implemented Taxjar and Added Payment Processing Messages #691